services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=data_platform_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-2nd-db.sql:/docker-entrypoint-initdb.d/init-2nd-db.sql #this will create the 2nd DB (local data warehouse)
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:

