"""create_incident_embeddings_table

Revision ID: d8b82acd59ee
Revises: 43e320d54440
Create Date: 2026-06-11 21:24:56.918862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'd8b82acd59ee'
down_revision: Union[str, Sequence[str], None] = '43e320d54440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.execute() is used because Alembic has no first-class op for CREATE EXTENSION. IF NOT EXISTS makes this idempotent, safe to re-run, no-op if the extension is already present.
    #This MUST run before the table is created, because the Vector column type below depends on the extension being available.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    #we use Vector(768) directly here, the pgvector SQLAlchemy package extends Alembic's type system so it knows how to render this as Postgres DDL.
    op.create_table('incident_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_embeddings_source_type'), 'incident_embeddings', ['source_type'], unique=False)
    op.create_index(op.f('ix_incident_embeddings_tenant_id'), 'incident_embeddings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    #STEP 4: the HNSW vector index on the embedding column.
    #USING hnsw is pgvector-specific, op.create_index doesn't natively support it, so we drop to raw SQL.
    #vector_cosine_ops tells the index to use cosine distance for similarity. This MUST match the operator we use at query time (<=>). 
    #If we ever switch to L2 distance (<->) or inner product (<#>), the operator class here has to change accordingly.
    #default HNSW parameters (m=16, ef_construction=64) are fine for our corpus size, tunable later if retrieval quality demands it.
    #HNSW indexes can be created on an empty table; the first inserts will build the index incrementally.
    op.execute(
        "CREATE INDEX ix_incident_embeddings_embedding_hnsw "
        "ON incident_embeddings USING hnsw (embedding vector_cosine_ops)"
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #reverse order: drop indexes, then table, then extension.
    #we drop the HNSW index explicitly even though drop_table would cascade, being explicit makes the downgrade readable and parallel to the upgrade.
    op.execute("DROP INDEX IF EXISTS ix_incident_embeddings_embedding_hnsw")

    op.drop_index(op.f('ix_incident_embeddings_tenant_id'), table_name='incident_embeddings')
    op.drop_index(op.f('ix_incident_embeddings_source_type'), table_name='incident_embeddings')
    op.drop_table('incident_embeddings')
    # ### end Alembic commands ###

    #we do NOT drop the pgvector extension in downgrade. Other migrations or tables may eventually depend on it. The extension is a one-time database-level setup.